config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "pages#home"
  resources :matchdays, only: :show do
    patch :update_predictions, on: :member
    resources :games, only: :show do
      resources :predictions, only: [:edit, :update]
    end
  end
  resources :users, only: :show do
    patch :algo, on: :member
  end
  resources :predictions, only: :create
  resources :clubs, only: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/club.rb
class Club < ApplicationRecord
  has_many :home_games, class_name: "Game", foreign_key: :home_team_id, dependent: :destroy
  has_many :away_games, class_name: "Game", foreign_key: :away_team_id, dependent: :destroy
  validates :points, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :goals_scored, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :goals_against, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :name, presence: true

  COUNTRIES = {
    "England" => 5,
    "Spain" => 5,
    "Germany" => 5,
    "Italy" => 5,
    "France" => 4,
    "Netherlands" => 4,
    "Portugal" => 4,
    "Ukraine" => 3,
    "Belgium" => 3,
    "Austria" => 3,
    "Scotland" => 2,
    "Serbia" => 2,
    "Czech Republic" => 2,
    "Slovakia" => 1,
    "Switzerland" => 1,
    "Croatia" => 1,
  }

  def games
    Game.where("home_team_id = ? OR away_team_id = ?", self.id, self.id)
  end

  def predictions(user)
    Prediction.where(game: games, user: user)
  end

  def update_points(user)
    self.points = 0
    self.goals_scored = 0
    self.goals_against = 0
    self.predictions(user).each do |prediction|
      prediction.game.home_team == self ? self.goals_scored += prediction.home_score : self.goals_scored += prediction.away_score
      prediction.game.home_team == self ? self.goals_against += prediction.away_score : self.goals_against += prediction.home_score
      calculate_points(prediction)
    end
    save
  end

  def calculate_points(prediction)
    if prediction.home_score == prediction.away_score
      self.points += 1
    elsif prediction.game.home_team == self && prediction.home_score > prediction.away_score
      self.points += 3
    elsif prediction.game.away_team == self && prediction.away_score > prediction.home_score
      self.points += 3
    end
  end

  def self.rankings
    Club.includes(:home_games, :away_games).all.sort_by { |club| [club.points, club.goals_scored - club.goals_against] }.reverse
  end
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :matchday
  belongs_to :home_team, class_name: "Club", foreign_key: :home_team_id
  belongs_to :away_team, class_name: "Club", foreign_key: :away_team_id
  validates :home_score, numericality: { only_integer: true, greater_than_or_equal_to: 0 }, allow_nil: true
  validates :away_score, numericality: { only_integer: true, greater_than_or_equal_to: 0 }, allow_nil: true
  after_update :update_points

  def prediction(user)
    Prediction.find_by(user: user, game: self)
  end

  def name
    "#{home_team.name} - #{away_team.name}"
  end

  def date
    day_of_week = gametime.wday
    day_names = %w(Sunday Monday Tuesday Wednesday Thursday Friday Saturday)
    day_name = day_names[day_of_week]
    day_name
  end

  def hour
    gametime.in_time_zone("Paris").strftime("%H:%M")
  end

  def update_points
    if home_score.nil? || away_score.nil?
      return
    else
      Prediction.where(game: self).each do |prediction|
        prediction.update!(home_score: home_score, away_score: away_score)
      end
    end
  end
end

app/models/matchday.rb
class Matchday < ApplicationRecord
  has_many :games
  scope :next, -> { where('end_date > ?', DateTime.now).first }

  def round
    Matchday.all.find_index(self) + 1
  end
end

app/models/prediction.rb
class Prediction < ApplicationRecord
  belongs_to :user
  belongs_to :game
  after_update :update_rankings

  def update_rankings
    game.home_team.update_points(user)
    game.away_team.update_points(user)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :predictions, dependent: :destroy
  after_create :create_predictions

  def create_predictions
    Game.all.each do |game|
      Prediction.create!(user: self, game: game, home_score: 0, away_score: 0)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/matchdays_controller.rb
class MatchdaysController < ApplicationController
  include MatchdaysHelper

  def show
    @clubs = Club.select(:id, :name, :points, :goals_against, :goals_scored).rankings
    @matchdays = Matchday.all
    @matchday = Matchday.find(params[:id])
    @games = @matchday.games.includes(:home_team, :away_team).order(:gametime)
  end

  def update_predictions
    @matchday = Matchday.find(params[:id])

    params[:matchday].each do |game_id, game_params|
      game = Game.find(game_id.to_i)
      prediction = game.prediction(current_user)
      prediction.update(game_params.permit(:home_score, :away_score))
      game.home_team.update_points(current_user)
      game.away_team.update_points(current_user)
    end

    @clubs = Club.select(:id, :name, :points, :goals_against, :goals_scored).rankings

    respond_to do |format|
      format.html { redirect_to matchday_path(@matchday) } # Pour les requêtes standards
      format.js { render partial: "table", locals: { clubs: @clubs } } # Pour AJAX
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @matchday = Matchday.next
    @user = current_user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def algo
    @user = current_user
    @matchdays = Matchday.all
    @matchdays.each do |matchday|
      PredictionAlgorithm.new(matchday, @user).call
    end
    redirect_to matchday_path(Matchday.next)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/date_helper.rb
module DateHelper
end

app/helpers/matchdays_helper.rb
module MatchdaysHelper
  def ranking_color(index)
    case index
    when 0..7
      index.even? ? "bg-green-600" : "bg-green-800"
    when 8..23
      index.even? ? "bg-gray-800" : "bg-gray-600"
    when 24..35
      index.even? ? "bg-red-800" : "bg-red-600"
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_spinner.html.erb
<div id="spinner" class="hidden fixed left-0 top-0 z-50 h-full w-full bg-white opacity-90 flex items-center justify-center">
  <div>
    <div class="flex items-center justify-center">
      <svg class="animate-spin border-indigo-300" xmlns="http://www.w3.org/2000/svg" width="62" height="60" viewBox="0 0 62 60" fill="none">
        <g id="Group 1000003705">
          <path id="Ellipse 713" d="M57.8203 26.9786L61.0693 4.11423L39.6437 12.7327L57.8203 26.9786ZM23.8447 59.327C24.9258 59.5537 25.9859 58.8612 26.2127 57.7801C26.4394 56.6991 25.7469 55.6389 24.6658 55.4122L23.8447 59.327ZM53.7345 11.6632C50.3561 7.28607 45.8331 3.92839 40.6655 1.96138L39.2425 5.69971C43.7207 7.40431 47.6403 10.314 50.568 14.1072L53.7345 11.6632ZM40.6655 1.96138C35.4979 -0.00563836 29.887 -0.505368 24.4532 0.517433L25.1931 4.4484C29.902 3.56205 34.7644 3.99511 39.2425 5.69971L40.6655 1.96138ZM24.4532 0.517433C19.0193 1.54023 13.9741 4.04573 9.87528 7.75693L12.56 10.7221C16.112 7.50599 20.4841 5.33475 25.1931 4.4484L24.4532 0.517433ZM9.87528 7.75693C5.77649 11.4681 2.78376 16.2405 1.22796 21.5464L5.06635 22.6719C6.41459 18.0738 9.00806 13.9382 12.56 10.7221L9.87528 7.75693ZM1.22796 21.5464C-0.327842 26.8523 -0.386119 32.4851 1.05957 37.822L4.92043 36.7762C3.66761 32.1512 3.71811 27.2699 5.06635 22.6719L1.22796 21.5464ZM1.05957 37.822C2.50526 43.159 5.3986 47.9922 9.41974 51.7874L12.1653 48.8785C8.68059 45.5896 6.17325 41.4011 4.92043 36.7762L1.05957 37.822ZM9.41974 51.7874C13.4409 55.5826 18.4332 58.192 23.8447 59.327L24.6658 55.4122C19.9762 54.4286 15.6499 52.1674 12.1653 48.8785L9.41974 51.7874Z" fill="#4F46E5" />
          <path id="Ellipse 714" d="M30.0007 58.0016C37.2836 58.0016 44.2797 55.1622 49.5026 50.0864C54.7255 45.0107 57.7638 38.0987 57.972 30.8187" stroke="#A5B4FC" stroke-width="4" stroke-linecap="round" stroke-dasharray="3 6" />
        </g>
      </svg>
    </div>
    <span class="text-black leading-snug">Loading...</span>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UclSimulator</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-uclbluedark text-white">
    <%= render "layouts/spinner" %>
    <div class="container mx-auto">
      <%= render "shared/navbar" %>
      <h1 class="text-center mt-28 mx-5"> Simulate all 2024-2025 UEFA Champions League games!</h1>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>

app/views/matchdays/_game.html.erb
<div class="bg-uclblue px-4 py-5 rounded-lg md:h-60 sm:h-40">
  <p class="text-center"><%= game.date %> <%= game.hour %></p>
  <div class="flex items-center justify-between">
    <%= f.simple_fields_for game.id.to_s, prediction do |ff| %>
      <div class="team flex flex-col-reverse items-center justify-center">
        <%= image_tag game.home_team.logo, width: 70, class: "max-h-20" %>
        <%= ff.label :home_score, game.home_team.name, class: "pb-3 text-wrap text-center" %>
      </div>
      <% if game.home_score && game.away_score %>
        <div class="w-12 bg-uclblue text-white text-center text-xl">
          <%= game.home_score %>
        </div>
        <div class="w-12 bg-uclblue text-white text-center text-xl">
          <%= game.away_score %>
        </div>
      <% else %>
        <%= ff.input :home_score, as: :string, label: false, input_html: { class: "w-12 bg-uclbluedark text-white border-uclbluelight rounded-lg text-center text-xl", data: {action: "change->update-rankings#update"} } %>

        <%= ff.input :away_score, as: :string, label: false, input_html: { class: "w-12 bg-uclbluedark text-white border-uclbluelight rounded-lg text-center text-xl", data: {action: "change->update-rankings#update"} } %>
      <% end %>
      <div class="team flex flex-col-reverse items-center justify-center">
        <%= image_tag game.away_team.logo, width: 70, class: "max-h-20" %>
        <%= ff.label :away_score, game.away_team.name, class: "pb-3 text-wrap text-center" %>
      </div>
    <% end %>
  </div>
</div>

app/views/matchdays/_horizontal_list.erb
<% matchdays.each_with_index do |matchday, index| %>
  <div class="day">
    <p>Matchday <%= index + 1 %></p>
    <p><%= matchday.start_date %> - <%= matchday.end_date %></p>
  </div>
<% end %>

app/views/matchdays/_horizontal_list.html.erb
<ul class="flex -mb-px text-sm font-medium text-center" id="default-tab" data-tabs-toggle="#default-tab-content" role="tablist">
  <% matchdays.each_with_index do |matchday, index| %>
    <li class="me-2" role="presentation">
      <button
        class="inline-flex p-4 border-b-2 rounded-t-lg"
        id="matchday<%= matchday.id %>-tab"
        data-action = "click->tabs#activate"
        data-tabs-target="#matchday<%= matchday.id %>"
        type="button"
        role="tab"
        aria-controls="matchday<%= matchday.id %>"
        aria-selected="false"
      >
        <div>
          <p>Matchday <%= index + 1 %></p>
          <p><%= matchday.start_date %> - <%= matchday.end_date %></p>
        </div>
      </button>
    </li>
  <% end %>
</ul>

app/views/matchdays/_predictions.html.erb
<div class="grid md:grid-cols-2 gap-4" data-controller="update-rankings">
  <% games.each do |game| %>
    <%= render 'game', game: game, prediction: game.prediction(current_user), f: f %>
  <% end %>
</div>

app/views/matchdays/_table.html.erb
<div>
  <table class="text-sm text-left sm:mt-5">
    <thead>
      <tr>
        <th scope="col" class="px-2 py-1">Pos</th>
        <th scope="col" class="px-2 py-1">Team</th>
        <th scope="col" class="px-2 py-1">GP</th>
        <th scope="col" class="px-2 py-1">Points</th>
        <th scope="col" class="px-2 py-1">GS</th>
        <th scope="col" class="px-2 py-1">GA</th>
        <th scope="col" class="px-2 py-1">GD</th>
      </tr>
    </thead>
    <tbody>
      <% clubs.each_with_index do |club, index| %>
        <tr class="border-b <%= ranking_color(index) %>">
          <td class="px-2 py-1"><%= index + 1 %></td>
          <td class="px-2 py-1"><%= club.name %></td>
          <td class="px-2 py-1"><%= club.games.size %></td>
          <td class="px-2 py-1"><%= club.points %></td>
          <td class="px-2 py-1"><%= club.goals_scored %></td>
          <td class="px-2 py-1"><%= club.goals_against %></td>
          <td class="px-2 py-1"><%= club.goals_scored - club.goals_against %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/matchdays/show.html.erb
<div class="container matchday-container" data-controller="tabs">
  <div class="summary mb-4 border-b">
    <%= render "horizontal_list", matchdays: @matchdays %>
  </div>

  <div class="md:grid md:grid-cols-3 gap-5">
    <div class="md:col-span-2">
      <% @matchdays.each do |matchday| %>
        <div
          class="<%= "hidden" unless matchday == Matchday.next %>"
          id="matchday<%= matchday.id %>"
          role="tabpanel"
          aria-labelledby="matchday<%= matchday.id %>-tab"
        >
          <%= simple_form_for matchday, url: update_predictions_matchday_path(matchday), method: :patch, remote: true do |f| %>
            <%= render "predictions", matchday: matchday, games: matchday.games.order(:gametime), f:f %>
          <% end %>
        </div>
      <% end %>
    </div>

    <div class="table-container">
      <%= render "table", clubs: @clubs %>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="max-w-screen-xl mx-5">
  <div class="buttons flex justify-center mt-10 mb-20 text-center">
    <% if @user %>
      <div class="homebutton px-5 py-3 text-base font-medium text-center inline-flex items-center justify-center w-full sm:w-auto text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800 mr-2">
        <i class="fas fa-search mr-2"></i>
        <%= link_to "Predict all games", matchday_path(@matchday), class: "w-full text-center" %>
      </div>
      <div class="homebutton px-5 py-3 text-base font-medium text-center inline-flex items-center justify-center w-full sm:w-auto text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800 ml-2">
        <i class="fa-solid fa-forward-fast mr-2"></i>
        <%= form_with url: algo_user_path(@user), method: :patch, class: "w-full text-center", data: { controller: "spinner", action: "submit->spinner#show" } do %>
          <%= submit_tag "Simulate all games", class: "cursor-pointer" %>
        <% end %>
      </div>
    <% else %>
      <div class="homebutton px-5 py-3 text-base font-medium text-center inline-flex items-center justify-center w-full sm:w-auto text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
        <%= link_to "Sign in to predict all games", new_user_session_path %>
      </div>
    <% end %>
  </div>
  <p class="text-center my-5 text-xl font-semibold underline my-10">Make your predictions for the group phase of the 2024 UEFA Champions League</h1>
  <p class ="text-justify">Your club has a tough draw and you wonder if they can make it to the next phase of the UEFA Champions League? Make your own predictions and check out which teams will come out on top of the league phase and qualify directly for the round of 16, which teams will have to go through the play-in game and who will be eliminated from the 2024-2025 Champions League. Or let our algorythm do the trick and see (and modify if you're unhappy) the results!</p>
</div>

app/views/shared/_navbar.html.erb
<nav class="bg-white dark:bg-gray-900 fixed w-full z-20 top-0 start-0 border-b border-gray-200 dark:border-gray-600">
  <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
    <a href=<%= root_path %> class="flex items-center space-x-3 rtl:space-x-reverse">
      <%= image_tag("UCL.svg", size: "40x25", alt: "Edit Entry") %>
      <span class="text-uclbluedark self-center text-2xl font-semibold whitespace-nowrap dark:text-white">UCL Simulator</span>
    </a>
    <% if current_user %>
      <div class="flex md:order-2 space-x-3 md:space-x-0 rtl:space-x-reverse">
        <%= link_to "Log out", destroy_user_session_path(), data: { "turbo-method": :delete }, class: "text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" %>
      </div>
    <% else %>
      <div class="flex md:order-2 space-x-3 md:space-x-0 rtl:space-x-reverse">
        <%= link_to "Log in", new_user_session_path(), class: "text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" %>
      </div>
    <% end %>
  </div>
</nav>